version: "3"
services:
  mqnamesrv:
    image: foxiswho/rocketmq:4.8.0
    container_name: mqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./logs:/home/rocketmq/logs
      - ./store:/home/rocketmq/store  
    environment:
      JAVA_OPT: -server -Xms128m -Xmx128m
    command: sh mqnamesrv
  mqbroker:
    image: foxiswho/rocketmq:4.8.0
    container_name: mqbroker
    ports:
      - 10911:10911
      - 10909:10909
    volumes:
      - ./logs:/home/rocketmq/logs
      - ./store:/home/rocketmq/store 
      - ./conf/broker.conf:/home/rocketmq/conf/broker.conf
    environment:
      NAMESRV_ADDR: mqnamesrv:9876
      JAVA_OPT_EXT: -server -Xms256m -Xmx256m -Xmn128m
    command: sh mqbroker -n mqnamesrv:9876 -c /home/rocketmq/conf/broker.conf
    depends_on:
      - mqnamesrv
  mqconsole:
    image: styletang/rocketmq-console-ng
    container_name: mqconsole
    ports:
      - 19876:8080
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=mqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    depends_on:
      - mqnamesrv