services:
  user-Service:
    image: userms:5.0
    container_name: userms
    ports:
      - "6066:6062"
    volumes:
      - /app/userMsDocker/tmp:/tmp
    networks: 
      - hsp_net
    command: ./wait-for-it.sh nacos:8848 -t 0 -- java -jar /user_ms_docker.jar
    depends_on: 
      - redis
      - mysql
      - nacos

  redis:
    image: redis
    ports:
      - "6381:6379"
    volumes:
      - /app/redis/data:/data
    networks: 
      - hsp_net
    command: --appendonly yes

  nacos:
    image: nacos/nacos-server
    environment:
      MODE: 'standalone'
    ports:
      - "8849:8848"
    networks: 
      - hsp_net
      
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
       - "3307:3306"
    volumes:
       - /app/mysql/master/log:/var/log/mysql
       - /app/mysql/master/data:/var/lib/mysql
       - /app/mysql/master/conf:/etc/mysql/conf.d
    networks:
      - hsp_net

networks: 
   hsp_net: 
