version: '3.7'

services:
  minio-base:
    image: minio/minio:RELEASE.2021-04-06T23-11-00Z
    hostname: "minio"
    container_name: minio-base
    restart: always
    networks:
      - sjs-net
    command: server /data
    ports:
      - "9000:9000" 
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: mypassword
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: b90Qz4RF8IntFGBX
    volumes:
      - ./data:/data


#自定义网络
networks:
  sjs-net:
    external: true


