### 注意：要在admin下创建子账号进行远程连接，比如使用DataX同步数据
version: '3'
services:
  mongodb:
    image: mongo:4.2.6
    container_name: mongodb
    environment:
      TZ: Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: mongodb
      MONGO_USERNAME: admin
      MONGO_PASSWORD: 123456
    restart: always
    networks:
      - sjs-net
    volumes:
      - ./data/db:/data/db
      - ./data/logs:/var/log/mongodb
      - ./data/config:/etc/mongo
      - ./js/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 28081:8081
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456
      - ME_CONFIG_MONGODB_SERVER=mongodb  
    networks:
      - sjs-net

#自定义网络
networks:
  sjs-net:
    external: true
