version: '3.5'
services:
  redis:
    image: redis:latest
    container_name: tsl_redis
    command: redis-server --requirepass Sjs.379=
    networks:
      - sjs-net
    restart: always
    ports:
      - "9017:6379"
    volumes:
      - ./data:/data
      # 替换容器内redis.conf
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf


#自定义网络
networks:
  sjs-net:
    external: true



